### ISSUE TITLE
Error classes

### ISSUE THREAD

**Issue by musketeer-eng-team** [IBM/castor-messaging#34]
### Summary

Define error classes.

### Justification

In order to capture and handle in a custom way the error that occur.

### Example

fflapi.py:

class ServerError(ValueError):
    pass

class BadRequestError(ValueError):
    pass

…
if 'error' in result:
	raise ServerError(result['error'])

if 'calls' not in result:
	raise BadRequestError("Malformed object: " + str(result))

controller.py:

from pycloudmessenger.ffl.fflapi import ServerError
from pycloudmessenger.ffl.fflapi import BadRequestError

@app.errorhandler(ServerError)
def server_error(error):
    return jsonify({'message': str(error)}), 500, {'ContentType': 'application/json'}

@app.errorhandler(BadRequestError)
def server_error(error):
    return jsonify({'message': str(error)}), 400, {'ContentType': 'application/json'}

**Comment by mkpurcell** [comment]
Fixed in version 0.3.0
