### ISSUE TITLE
Task additional user info

### ISSUE THREAD

**Issue by musketeer-eng-team** [IBM/castor-messaging#36]
### Summary

Make sure you know which tasks the user is participating in and which tasks he is creator of.

### Justification

So that you can filter and know which tasks a user is involved in.

### Example

We've identified two solutions:

1) Make sure that within the task model you know which tasks the user is participating in and the ones he is creator of: by name/id or boolean (the model could also be a DTO)

2) Have a get_tasks_by_user method to return a lists of tasks for which the user is a participant or aggregator

**Comment by mkpurcell** [comment]
pycloudmessenger.fflapi.Users.get_joined_tasks already exists
pycloudmessenger.fflapi.Users.get_created_tasks added in version 0.3.0
