### ISSUE TITLE
Avoid conversion of numpy array messages into lists

### ISSUE THREAD

**Issue by mathsinn** [IBM/castor-messaging#39]
Currently, when an numpy array is part of a sent message, the receiver will receive it as list. Could such implicit transformation be avoided?

**Comment by minhitbk** [comment]
@marferdiaz: Could you please specify the lines where it happens, i don't see where numpy arrays are splitted to list in the send/receive functions.

**Comment by marferdiaz** [comment]
Sure, it happens for the local communications, in localapi.py line 38 (inside class NumpyEncoder).

**Comment by minhitbk** [comment]
> Sure, it happens for the local communications, in localapi.py line 38 (inside class NumpyEncoder).

Thank you @marferdiaz , it's solved in https://github.com/IBM/Musketeer-Client/pull/10, which will be soon merged to the master branch of Musketeer-Client.
