### ISSUE TITLE
Additional task status

### ISSUE THREAD

**Issue by musketeer-eng-team** [IBM/castor-messaging#52]
### Summary

It would be helpful to have an intermediate status between CREATED and STARTED.

### Justification

When a new task is added to the available ones it gets the CREATED status. As soon as its owner decides
to start the aggregation on the background the master waits for the workers number to reach the task quorum
in order to start the federated learning. Nevertheless, during this time the task status remains the same,
changing to STARTED only when the actual task execution starts. In this way, there is no way for other users
to understand whether that task owner has started the aggregation or not, getting an error if they choose
to join a task which has just been created and not yet aggregated.

### "Must have" functionality

The additional task status (something like "PENDING") would have multiple benefits:

* Aggregator receives a real feedback after the aggregation by checking the task status.
* All the "participant" calls on tasks which are not waiting for workers are avoided.
* Improved browsing on the tasks list.

**Comment by mkpurcell** [comment]
Now available since release 0.7.3.
